[build]
target = "riscv32ec-unknown-none-elf.json"

[target.riscv32ec-unknown-none-elf]
rustflags = [
    "-C",
    "linker=riscv32-unknown-elf-gcc",
    "-C",
    "link-arg=-Wl,-Tmemory.x",
    "-C",
    "link-arg=-Wl,-Tlink.x",
    "-C",
    "link-arg=-nostartfiles",
]

[target.riscv32ic-unknown-none-elf]
rustflags = [
    "-C",
    "linker=riscv32-unknown-elf-gcc",
    "-C",
    "link-arg=-Wl,-Tmemory.x",
    "-C",
    "link-arg=-Wl,-Tlink.x",
    "-C",
    "link-arg=-nostartfiles",
]

[unstable]
build-std = ["core"]
