[build]
target = "riscv32emc-unknown-eabi.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.riscv32emc-unknown-eabi]
rustflags = [
    "-C",
    "linker=riscv32-unknown-elf-gcc",
    "-C",
    "link-arg=-Wl,-Tmemory.x",
    "-C",
    "link-arg=-Wl,-Tlink.x",
    "-C",
    "link-arg=-nostartfiles",
    "-C",
    "link-arg=-march=rv32emc",
    "-C",
    "link-arg=-mabi=ilp32e"
]
runner = "../run-sim.sh"
